// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: proto/coordinator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoordinatorPutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ctx           *ContextProto          `protobuf:"bytes,3,opt,name=ctx,proto3" json:"ctx,omitempty"` // optional client context
	W             uint32                 `protobuf:"varint,4,opt,name=W,proto3" json:"W,omitempty"`    // optional override for write quorum (0 -> use default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorPutReq) Reset() {
	*x = CoordinatorPutReq{}
	mi := &file_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorPutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorPutReq) ProtoMessage() {}

func (x *CoordinatorPutReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorPutReq.ProtoReflect.Descriptor instead.
func (*CoordinatorPutReq) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinatorPutReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CoordinatorPutReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CoordinatorPutReq) GetCtx() *ContextProto {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *CoordinatorPutReq) GetW() uint32 {
	if x != nil {
		return x.W
	}
	return 0
}

type CoordinatorPutResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Err            string                 `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	StoredContexts []*ContextProto        `protobuf:"bytes,2,rep,name=StoredContexts,proto3" json:"StoredContexts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CoordinatorPutResp) Reset() {
	*x = CoordinatorPutResp{}
	mi := &file_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorPutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorPutResp) ProtoMessage() {}

func (x *CoordinatorPutResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorPutResp.ProtoReflect.Descriptor instead.
func (*CoordinatorPutResp) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorPutResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *CoordinatorPutResp) GetStoredContexts() []*ContextProto {
	if x != nil {
		return x.StoredContexts
	}
	return nil
}

type CoordinatorGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	R             uint32                 `protobuf:"varint,2,opt,name=R,proto3" json:"R,omitempty"` // optional override for read quorum (0 -> use default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorGetReq) Reset() {
	*x = CoordinatorGetReq{}
	mi := &file_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorGetReq) ProtoMessage() {}

func (x *CoordinatorGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorGetReq.ProtoReflect.Descriptor instead.
func (*CoordinatorGetReq) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinatorGetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CoordinatorGetReq) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

type CoordinatorGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	Items         []*ItemProto           `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorGetResp) Reset() {
	*x = CoordinatorGetResp{}
	mi := &file_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorGetResp) ProtoMessage() {}

func (x *CoordinatorGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorGetResp.ProtoReflect.Descriptor instead.
func (*CoordinatorGetResp) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *CoordinatorGetResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *CoordinatorGetResp) GetItems() []*ItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

// Reuse / duplicate of your Item/Context proto definitions (ensure these match existing proto types)
type ItemProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Ctx           *ContextProto          `protobuf:"bytes,3,opt,name=Ctx,proto3" json:"Ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemProto) Reset() {
	*x = ItemProto{}
	mi := &file_proto_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemProto) ProtoMessage() {}

func (x *ItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemProto.ProtoReflect.Descriptor instead.
func (*ItemProto) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *ItemProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ItemProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ItemProto) GetCtx() *ContextProto {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type ContextProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*VClockEntry         `protobuf:"bytes,1,rep,name=Entries,proto3" json:"Entries,omitempty"`
	Tombstone     bool                   `protobuf:"varint,2,opt,name=Tombstone,proto3" json:"Tombstone,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=Origin,proto3" json:"Origin,omitempty"`
	Ts            int64                  `protobuf:"varint,4,opt,name=Ts,proto3" json:"Ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextProto) Reset() {
	*x = ContextProto{}
	mi := &file_proto_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextProto) ProtoMessage() {}

func (x *ContextProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextProto.ProtoReflect.Descriptor instead.
func (*ContextProto) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *ContextProto) GetEntries() []*VClockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ContextProto) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *ContextProto) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ContextProto) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type VClockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=Node,proto3" json:"Node,omitempty"`
	Counter       uint64                 `protobuf:"varint,2,opt,name=Counter,proto3" json:"Counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VClockEntry) Reset() {
	*x = VClockEntry{}
	mi := &file_proto_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VClockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VClockEntry) ProtoMessage() {}

func (x *VClockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VClockEntry.ProtoReflect.Descriptor instead.
func (*VClockEntry) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *VClockEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VClockEntry) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

var File_proto_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coordinator.proto\x12\x06dynamo\"q\n" +
	"\x11CoordinatorPutReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12&\n" +
	"\x03ctx\x18\x03 \x01(\v2\x14.dynamo.ContextProtoR\x03ctx\x12\f\n" +
	"\x01W\x18\x04 \x01(\rR\x01W\"d\n" +
	"\x12CoordinatorPutResp\x12\x10\n" +
	"\x03Err\x18\x01 \x01(\tR\x03Err\x12<\n" +
	"\x0eStoredContexts\x18\x02 \x03(\v2\x14.dynamo.ContextProtoR\x0eStoredContexts\"3\n" +
	"\x11CoordinatorGetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\f\n" +
	"\x01R\x18\x02 \x01(\rR\x01R\"O\n" +
	"\x12CoordinatorGetResp\x12\x10\n" +
	"\x03Err\x18\x01 \x01(\tR\x03Err\x12'\n" +
	"\x05Items\x18\x02 \x03(\v2\x11.dynamo.ItemProtoR\x05Items\"[\n" +
	"\tItemProto\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\fR\x05Value\x12&\n" +
	"\x03Ctx\x18\x03 \x01(\v2\x14.dynamo.ContextProtoR\x03Ctx\"\x83\x01\n" +
	"\fContextProto\x12-\n" +
	"\aEntries\x18\x01 \x03(\v2\x13.dynamo.VClockEntryR\aEntries\x12\x1c\n" +
	"\tTombstone\x18\x02 \x01(\bR\tTombstone\x12\x16\n" +
	"\x06Origin\x18\x03 \x01(\tR\x06Origin\x12\x0e\n" +
	"\x02Ts\x18\x04 \x01(\x03R\x02Ts\";\n" +
	"\vVClockEntry\x12\x12\n" +
	"\x04Node\x18\x01 \x01(\tR\x04Node\x12\x18\n" +
	"\aCounter\x18\x02 \x01(\x04R\aCounter2\x8d\x01\n" +
	"\vCoordinator\x12>\n" +
	"\x03Put\x12\x19.dynamo.CoordinatorPutReq\x1a\x1a.dynamo.CoordinatorPutResp\"\x00\x12>\n" +
	"\x03Get\x12\x19.dynamo.CoordinatorGetReq\x1a\x1a.dynamo.CoordinatorGetResp\"\x00B\x11Z\x0fdynamodb1/protob\x06proto3"

var (
	file_proto_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_proto_rawDescData
}

var file_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_coordinator_proto_goTypes = []any{
	(*CoordinatorPutReq)(nil),  // 0: dynamo.CoordinatorPutReq
	(*CoordinatorPutResp)(nil), // 1: dynamo.CoordinatorPutResp
	(*CoordinatorGetReq)(nil),  // 2: dynamo.CoordinatorGetReq
	(*CoordinatorGetResp)(nil), // 3: dynamo.CoordinatorGetResp
	(*ItemProto)(nil),          // 4: dynamo.ItemProto
	(*ContextProto)(nil),       // 5: dynamo.ContextProto
	(*VClockEntry)(nil),        // 6: dynamo.VClockEntry
}
var file_proto_coordinator_proto_depIdxs = []int32{
	5, // 0: dynamo.CoordinatorPutReq.ctx:type_name -> dynamo.ContextProto
	5, // 1: dynamo.CoordinatorPutResp.StoredContexts:type_name -> dynamo.ContextProto
	4, // 2: dynamo.CoordinatorGetResp.Items:type_name -> dynamo.ItemProto
	5, // 3: dynamo.ItemProto.Ctx:type_name -> dynamo.ContextProto
	6, // 4: dynamo.ContextProto.Entries:type_name -> dynamo.VClockEntry
	0, // 5: dynamo.Coordinator.Put:input_type -> dynamo.CoordinatorPutReq
	2, // 6: dynamo.Coordinator.Get:input_type -> dynamo.CoordinatorGetReq
	1, // 7: dynamo.Coordinator.Put:output_type -> dynamo.CoordinatorPutResp
	3, // 8: dynamo.Coordinator.Get:output_type -> dynamo.CoordinatorGetResp
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_coordinator_proto_init() }
func file_proto_coordinator_proto_init() {
	if File_proto_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_proto_depIdxs,
		MessageInfos:      file_proto_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_proto = out.File
	file_proto_coordinator_proto_goTypes = nil
	file_proto_coordinator_proto_depIdxs = nil
}
