// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: dynamo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VClockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Counter       uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VClockEntry) Reset() {
	*x = VClockEntry{}
	mi := &file_dynamo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VClockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VClockEntry) ProtoMessage() {}

func (x *VClockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VClockEntry.ProtoReflect.Descriptor instead.
func (*VClockEntry) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{0}
}

func (x *VClockEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VClockEntry) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type ContextProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*VClockEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Tombstone     bool                   `protobuf:"varint,2,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Ts            int64                  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextProto) Reset() {
	*x = ContextProto{}
	mi := &file_dynamo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextProto) ProtoMessage() {}

func (x *ContextProto) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextProto.ProtoReflect.Descriptor instead.
func (*ContextProto) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{1}
}

func (x *ContextProto) GetEntries() []*VClockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ContextProto) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *ContextProto) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ContextProto) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type ItemProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ctx           *ContextProto          `protobuf:"bytes,3,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemProto) Reset() {
	*x = ItemProto{}
	mi := &file_dynamo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemProto) ProtoMessage() {}

func (x *ItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemProto.ProtoReflect.Descriptor instead.
func (*ItemProto) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{2}
}

func (x *ItemProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ItemProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ItemProto) GetCtx() *ContextProto {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type ReplicaPutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ItemProto             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaPutReq) Reset() {
	*x = ReplicaPutReq{}
	mi := &file_dynamo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaPutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaPutReq) ProtoMessage() {}

func (x *ReplicaPutReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaPutReq.ProtoReflect.Descriptor instead.
func (*ReplicaPutReq) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicaPutReq) GetItem() *ItemProto {
	if x != nil {
		return x.Item
	}
	return nil
}

type ReplicaPutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stored        []*ItemProto           `protobuf:"bytes,1,rep,name=stored,proto3" json:"stored,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaPutResp) Reset() {
	*x = ReplicaPutResp{}
	mi := &file_dynamo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaPutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaPutResp) ProtoMessage() {}

func (x *ReplicaPutResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaPutResp.ProtoReflect.Descriptor instead.
func (*ReplicaPutResp) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicaPutResp) GetStored() []*ItemProto {
	if x != nil {
		return x.Stored
	}
	return nil
}

func (x *ReplicaPutResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ReplicaGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaGetReq) Reset() {
	*x = ReplicaGetReq{}
	mi := &file_dynamo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaGetReq) ProtoMessage() {}

func (x *ReplicaGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaGetReq.ProtoReflect.Descriptor instead.
func (*ReplicaGetReq) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicaGetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReplicaGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemProto           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaGetResp) Reset() {
	*x = ReplicaGetResp{}
	mi := &file_dynamo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaGetResp) ProtoMessage() {}

func (x *ReplicaGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaGetResp.ProtoReflect.Descriptor instead.
func (*ReplicaGetResp) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicaGetResp) GetItems() []*ItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReplicaGetResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_dynamo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{7}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_dynamo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{8}
}

func (x *PingResp) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type MerkleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vnode         string                 `protobuf:"bytes,1,opt,name=vnode,proto3" json:"vnode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleReq) Reset() {
	*x = MerkleReq{}
	mi := &file_dynamo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleReq) ProtoMessage() {}

func (x *MerkleReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleReq.ProtoReflect.Descriptor instead.
func (*MerkleReq) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{9}
}

func (x *MerkleReq) GetVnode() string {
	if x != nil {
		return x.Vnode
	}
	return ""
}

type MerkleChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vnode         string                 `protobuf:"bytes,1,opt,name=vnode,proto3" json:"vnode,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleChunk) Reset() {
	*x = MerkleChunk{}
	mi := &file_dynamo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleChunk) ProtoMessage() {}

func (x *MerkleChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleChunk.ProtoReflect.Descriptor instead.
func (*MerkleChunk) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{10}
}

func (x *MerkleChunk) GetVnode() string {
	if x != nil {
		return x.Vnode
	}
	return ""
}

func (x *MerkleChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ItemTransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemProto           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemTransferReq) Reset() {
	*x = ItemTransferReq{}
	mi := &file_dynamo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemTransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemTransferReq) ProtoMessage() {}

func (x *ItemTransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemTransferReq.ProtoReflect.Descriptor instead.
func (*ItemTransferReq) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{11}
}

func (x *ItemTransferReq) GetItems() []*ItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemTransferResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemTransferResp) Reset() {
	*x = ItemTransferResp{}
	mi := &file_dynamo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemTransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemTransferResp) ProtoMessage() {}

func (x *ItemTransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemTransferResp.ProtoReflect.Descriptor instead.
func (*ItemTransferResp) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{12}
}

func (x *ItemTransferResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StreamKeysReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vnode         string                 `protobuf:"bytes,1,opt,name=vnode,proto3" json:"vnode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamKeysReq) Reset() {
	*x = StreamKeysReq{}
	mi := &file_dynamo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamKeysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamKeysReq) ProtoMessage() {}

func (x *StreamKeysReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamKeysReq.ProtoReflect.Descriptor instead.
func (*StreamKeysReq) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{13}
}

func (x *StreamKeysReq) GetVnode() string {
	if x != nil {
		return x.Vnode
	}
	return ""
}

type StreamKeysChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemProto           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamKeysChunk) Reset() {
	*x = StreamKeysChunk{}
	mi := &file_dynamo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamKeysChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamKeysChunk) ProtoMessage() {}

func (x *StreamKeysChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamKeysChunk.ProtoReflect.Descriptor instead.
func (*StreamKeysChunk) Descriptor() ([]byte, []int) {
	return file_dynamo_proto_rawDescGZIP(), []int{14}
}

func (x *StreamKeysChunk) GetItems() []*ItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_dynamo_proto protoreflect.FileDescriptor

const file_dynamo_proto_rawDesc = "" +
	"\n" +
	"\fdynamo.proto\x12\tdynamodb1\";\n" +
	"\vVClockEntry\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\"\x86\x01\n" +
	"\fContextProto\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.dynamodb1.VClockEntryR\aentries\x12\x1c\n" +
	"\ttombstone\x18\x02 \x01(\bR\ttombstone\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\"^\n" +
	"\tItemProto\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12)\n" +
	"\x03ctx\x18\x03 \x01(\v2\x17.dynamodb1.ContextProtoR\x03ctx\"9\n" +
	"\rReplicaPutReq\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.dynamodb1.ItemProtoR\x04item\"P\n" +
	"\x0eReplicaPutResp\x12,\n" +
	"\x06stored\x18\x01 \x03(\v2\x14.dynamodb1.ItemProtoR\x06stored\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"!\n" +
	"\rReplicaGetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"N\n" +
	"\x0eReplicaGetResp\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.dynamodb1.ItemProtoR\x05items\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"\t\n" +
	"\aPingReq\"\x1e\n" +
	"\bPingResp\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"!\n" +
	"\tMerkleReq\x12\x14\n" +
	"\x05vnode\x18\x01 \x01(\tR\x05vnode\"9\n" +
	"\vMerkleChunk\x12\x14\n" +
	"\x05vnode\x18\x01 \x01(\tR\x05vnode\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"=\n" +
	"\x0fItemTransferReq\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.dynamodb1.ItemProtoR\x05items\"\"\n" +
	"\x10ItemTransferResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"%\n" +
	"\rStreamKeysReq\x12\x14\n" +
	"\x05vnode\x18\x01 \x01(\tR\x05vnode\"=\n" +
	"\x0fStreamKeysChunk\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.dynamodb1.ItemProtoR\x05items2\x9a\x03\n" +
	"\x06Dynamo\x12C\n" +
	"\n" +
	"ReplicaPut\x12\x18.dynamodb1.ReplicaPutReq\x1a\x19.dynamodb1.ReplicaPutResp\"\x00\x12C\n" +
	"\n" +
	"ReplicaGet\x12\x18.dynamodb1.ReplicaGetReq\x1a\x19.dynamodb1.ReplicaGetResp\"\x00\x121\n" +
	"\x04Ping\x12\x12.dynamodb1.PingReq\x1a\x13.dynamodb1.PingResp\"\x00\x12F\n" +
	"\n" +
	"StreamKeys\x12\x18.dynamodb1.StreamKeysReq\x1a\x1a.dynamodb1.StreamKeysChunk\"\x000\x01\x12@\n" +
	"\fStreamMerkle\x12\x14.dynamodb1.MerkleReq\x1a\x16.dynamodb1.MerkleChunk\"\x000\x01\x12I\n" +
	"\fTransferItem\x12\x1a.dynamodb1.ItemTransferReq\x1a\x1b.dynamodb1.ItemTransferResp\"\x00B\x17Z\x15dynamodb1/proto;protob\x06proto3"

var (
	file_dynamo_proto_rawDescOnce sync.Once
	file_dynamo_proto_rawDescData []byte
)

func file_dynamo_proto_rawDescGZIP() []byte {
	file_dynamo_proto_rawDescOnce.Do(func() {
		file_dynamo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamo_proto_rawDesc), len(file_dynamo_proto_rawDesc)))
	})
	return file_dynamo_proto_rawDescData
}

var file_dynamo_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_dynamo_proto_goTypes = []any{
	(*VClockEntry)(nil),      // 0: dynamodb1.VClockEntry
	(*ContextProto)(nil),     // 1: dynamodb1.ContextProto
	(*ItemProto)(nil),        // 2: dynamodb1.ItemProto
	(*ReplicaPutReq)(nil),    // 3: dynamodb1.ReplicaPutReq
	(*ReplicaPutResp)(nil),   // 4: dynamodb1.ReplicaPutResp
	(*ReplicaGetReq)(nil),    // 5: dynamodb1.ReplicaGetReq
	(*ReplicaGetResp)(nil),   // 6: dynamodb1.ReplicaGetResp
	(*PingReq)(nil),          // 7: dynamodb1.PingReq
	(*PingResp)(nil),         // 8: dynamodb1.PingResp
	(*MerkleReq)(nil),        // 9: dynamodb1.MerkleReq
	(*MerkleChunk)(nil),      // 10: dynamodb1.MerkleChunk
	(*ItemTransferReq)(nil),  // 11: dynamodb1.ItemTransferReq
	(*ItemTransferResp)(nil), // 12: dynamodb1.ItemTransferResp
	(*StreamKeysReq)(nil),    // 13: dynamodb1.StreamKeysReq
	(*StreamKeysChunk)(nil),  // 14: dynamodb1.StreamKeysChunk
}
var file_dynamo_proto_depIdxs = []int32{
	0,  // 0: dynamodb1.ContextProto.entries:type_name -> dynamodb1.VClockEntry
	1,  // 1: dynamodb1.ItemProto.ctx:type_name -> dynamodb1.ContextProto
	2,  // 2: dynamodb1.ReplicaPutReq.item:type_name -> dynamodb1.ItemProto
	2,  // 3: dynamodb1.ReplicaPutResp.stored:type_name -> dynamodb1.ItemProto
	2,  // 4: dynamodb1.ReplicaGetResp.items:type_name -> dynamodb1.ItemProto
	2,  // 5: dynamodb1.ItemTransferReq.items:type_name -> dynamodb1.ItemProto
	2,  // 6: dynamodb1.StreamKeysChunk.items:type_name -> dynamodb1.ItemProto
	3,  // 7: dynamodb1.Dynamo.ReplicaPut:input_type -> dynamodb1.ReplicaPutReq
	5,  // 8: dynamodb1.Dynamo.ReplicaGet:input_type -> dynamodb1.ReplicaGetReq
	7,  // 9: dynamodb1.Dynamo.Ping:input_type -> dynamodb1.PingReq
	13, // 10: dynamodb1.Dynamo.StreamKeys:input_type -> dynamodb1.StreamKeysReq
	9,  // 11: dynamodb1.Dynamo.StreamMerkle:input_type -> dynamodb1.MerkleReq
	11, // 12: dynamodb1.Dynamo.TransferItem:input_type -> dynamodb1.ItemTransferReq
	4,  // 13: dynamodb1.Dynamo.ReplicaPut:output_type -> dynamodb1.ReplicaPutResp
	6,  // 14: dynamodb1.Dynamo.ReplicaGet:output_type -> dynamodb1.ReplicaGetResp
	8,  // 15: dynamodb1.Dynamo.Ping:output_type -> dynamodb1.PingResp
	14, // 16: dynamodb1.Dynamo.StreamKeys:output_type -> dynamodb1.StreamKeysChunk
	10, // 17: dynamodb1.Dynamo.StreamMerkle:output_type -> dynamodb1.MerkleChunk
	12, // 18: dynamodb1.Dynamo.TransferItem:output_type -> dynamodb1.ItemTransferResp
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dynamo_proto_init() }
func file_dynamo_proto_init() {
	if File_dynamo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamo_proto_rawDesc), len(file_dynamo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dynamo_proto_goTypes,
		DependencyIndexes: file_dynamo_proto_depIdxs,
		MessageInfos:      file_dynamo_proto_msgTypes,
	}.Build()
	File_dynamo_proto = out.File
	file_dynamo_proto_goTypes = nil
	file_dynamo_proto_depIdxs = nil
}
