// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: dynamo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dynamo_ReplicaPut_FullMethodName   = "/dynamodb1.Dynamo/ReplicaPut"
	Dynamo_ReplicaGet_FullMethodName   = "/dynamodb1.Dynamo/ReplicaGet"
	Dynamo_Ping_FullMethodName         = "/dynamodb1.Dynamo/Ping"
	Dynamo_StreamKeys_FullMethodName   = "/dynamodb1.Dynamo/StreamKeys"
	Dynamo_StreamMerkle_FullMethodName = "/dynamodb1.Dynamo/StreamMerkle"
	Dynamo_TransferItem_FullMethodName = "/dynamodb1.Dynamo/TransferItem"
)

// DynamoClient is the client API for Dynamo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamoClient interface {
	ReplicaPut(ctx context.Context, in *ReplicaPutReq, opts ...grpc.CallOption) (*ReplicaPutResp, error)
	ReplicaGet(ctx context.Context, in *ReplicaGetReq, opts ...grpc.CallOption) (*ReplicaGetResp, error)
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	StreamKeys(ctx context.Context, in *StreamKeysReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamKeysChunk], error)
	StreamMerkle(ctx context.Context, in *MerkleReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MerkleChunk], error)
	TransferItem(ctx context.Context, in *ItemTransferReq, opts ...grpc.CallOption) (*ItemTransferResp, error)
}

type dynamoClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamoClient(cc grpc.ClientConnInterface) DynamoClient {
	return &dynamoClient{cc}
}

func (c *dynamoClient) ReplicaPut(ctx context.Context, in *ReplicaPutReq, opts ...grpc.CallOption) (*ReplicaPutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaPutResp)
	err := c.cc.Invoke(ctx, Dynamo_ReplicaPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoClient) ReplicaGet(ctx context.Context, in *ReplicaGetReq, opts ...grpc.CallOption) (*ReplicaGetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaGetResp)
	err := c.cc.Invoke(ctx, Dynamo_ReplicaGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, Dynamo_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoClient) StreamKeys(ctx context.Context, in *StreamKeysReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamKeysChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dynamo_ServiceDesc.Streams[0], Dynamo_StreamKeys_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamKeysReq, StreamKeysChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dynamo_StreamKeysClient = grpc.ServerStreamingClient[StreamKeysChunk]

func (c *dynamoClient) StreamMerkle(ctx context.Context, in *MerkleReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MerkleChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dynamo_ServiceDesc.Streams[1], Dynamo_StreamMerkle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MerkleReq, MerkleChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dynamo_StreamMerkleClient = grpc.ServerStreamingClient[MerkleChunk]

func (c *dynamoClient) TransferItem(ctx context.Context, in *ItemTransferReq, opts ...grpc.CallOption) (*ItemTransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemTransferResp)
	err := c.cc.Invoke(ctx, Dynamo_TransferItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamoServer is the server API for Dynamo service.
// All implementations must embed UnimplementedDynamoServer
// for forward compatibility.
type DynamoServer interface {
	ReplicaPut(context.Context, *ReplicaPutReq) (*ReplicaPutResp, error)
	ReplicaGet(context.Context, *ReplicaGetReq) (*ReplicaGetResp, error)
	Ping(context.Context, *PingReq) (*PingResp, error)
	StreamKeys(*StreamKeysReq, grpc.ServerStreamingServer[StreamKeysChunk]) error
	StreamMerkle(*MerkleReq, grpc.ServerStreamingServer[MerkleChunk]) error
	TransferItem(context.Context, *ItemTransferReq) (*ItemTransferResp, error)
	mustEmbedUnimplementedDynamoServer()
}

// UnimplementedDynamoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamoServer struct{}

func (UnimplementedDynamoServer) ReplicaPut(context.Context, *ReplicaPutReq) (*ReplicaPutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaPut not implemented")
}
func (UnimplementedDynamoServer) ReplicaGet(context.Context, *ReplicaGetReq) (*ReplicaGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaGet not implemented")
}
func (UnimplementedDynamoServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDynamoServer) StreamKeys(*StreamKeysReq, grpc.ServerStreamingServer[StreamKeysChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamKeys not implemented")
}
func (UnimplementedDynamoServer) StreamMerkle(*MerkleReq, grpc.ServerStreamingServer[MerkleChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMerkle not implemented")
}
func (UnimplementedDynamoServer) TransferItem(context.Context, *ItemTransferReq) (*ItemTransferResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferItem not implemented")
}
func (UnimplementedDynamoServer) mustEmbedUnimplementedDynamoServer() {}
func (UnimplementedDynamoServer) testEmbeddedByValue()                {}

// UnsafeDynamoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamoServer will
// result in compilation errors.
type UnsafeDynamoServer interface {
	mustEmbedUnimplementedDynamoServer()
}

func RegisterDynamoServer(s grpc.ServiceRegistrar, srv DynamoServer) {
	// If the following call pancis, it indicates UnimplementedDynamoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dynamo_ServiceDesc, srv)
}

func _Dynamo_ReplicaPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaPutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoServer).ReplicaPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamo_ReplicaPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoServer).ReplicaPut(ctx, req.(*ReplicaPutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamo_ReplicaGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoServer).ReplicaGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamo_ReplicaGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoServer).ReplicaGet(ctx, req.(*ReplicaGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamo_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dynamo_StreamKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamKeysReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DynamoServer).StreamKeys(m, &grpc.GenericServerStream[StreamKeysReq, StreamKeysChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dynamo_StreamKeysServer = grpc.ServerStreamingServer[StreamKeysChunk]

func _Dynamo_StreamMerkle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MerkleReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DynamoServer).StreamMerkle(m, &grpc.GenericServerStream[MerkleReq, MerkleChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dynamo_StreamMerkleServer = grpc.ServerStreamingServer[MerkleChunk]

func _Dynamo_TransferItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoServer).TransferItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dynamo_TransferItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoServer).TransferItem(ctx, req.(*ItemTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Dynamo_ServiceDesc is the grpc.ServiceDesc for Dynamo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dynamo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamodb1.Dynamo",
	HandlerType: (*DynamoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicaPut",
			Handler:    _Dynamo_ReplicaPut_Handler,
		},
		{
			MethodName: "ReplicaGet",
			Handler:    _Dynamo_ReplicaGet_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Dynamo_Ping_Handler,
		},
		{
			MethodName: "TransferItem",
			Handler:    _Dynamo_TransferItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamKeys",
			Handler:       _Dynamo_StreamKeys_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMerkle",
			Handler:       _Dynamo_StreamMerkle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dynamo.proto",
}
